CC=g++
CFLAGS=-std=c++0x -pthread -o
LDFLAGS=
SOURCES=main.cpp communication.cpp observer.cpp pathfinding.cpp pipe.cpp socket.cpp threads.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=lazyLegoCar

all: 
	$(CC) $(SOURCES) $(EXECUTABLE)
	
